### ISSUE TITLE
dist_cm hangs if no echo received

### ISSUE THREAD

**Issue by jerryneedell** [mmabey/CircuitPython_HCSR04#1]
If no echo is received the call to dist_cm()  will hang. See the discussion in this Forum post 
https://forums.adafruit.com/viewtopic.php?f=52&t=131188&start=15#p654534
One simple fix is to add a timeout as a keyword argument. Then use time.monotonic() to return a -1 if a timeout occurs.

I have tested this and it seems to be working well. My sensor was often hanging during the first sample.
This will also prevent it hanging if the sensor is not present.

I'll be happy to submit a PR if you think this is the right way to address this.

Here are some snippets of the changes I made

```
 def __init__(self, trig_pin, echo_pin,timeout=2):
  ...
        self.timeout=timeout
 ...
def _dist_two_wire(self):
        self.echo.clear()  # Discard any previous pulse values
        self.trig.value = 1  # Set trig high
        time.sleep(0.00001)  # 10 micro seconds 10/1000/1000
        self.trig.value = 0  # Set trig low
        timeout=time.monotonic()
        self.echo.resume()
        while len(self.echo) == 0:
            # Wait for a pulse
            if(time.monotonic()-timeout)>self.timeout:
                self.echo.pause()
                return -1
        self.echo.pause()
        if self.echo[0] == 65535:
            return -1

```

**Comment by mmabey** [comment]
Excellent catch! Sorry for the trouble this seems to have caused. I didn't have that kind of problem when I was developing it, but it's been awhile since I've worked with it. I'm happy that somebody out there is getting some use from my code.

Your fix looks great to me. The only suggestion I would give is to name the timeout argument as `timeout_sec` just to be more explicit as to its meaning. I would be happy to accept a PR with the patch.

**Comment by jerryneedell** [comment]
Thanks, your code was easy to read and modify,   I'll change the name of the argument as requested and I was wondering what to use for the default timeout. 2 seconds is a very long time. Of course, this is meant to correct for an anomaly in the system, so it is completely arbitrary. Would something like .5 seconds be a better default? Actual response time should always be a few 10s of ms including all delays. 

BTW - this discussion talks  about the differences between some of the better sensors and cheaper knock-offs. https://forum.arduino.cc/index.php?topic=55119.0  Apparently, some do have internal timeouts.  I have had much better behavior from the "SunFounder" devices than from some other ones.  Even so, my devices have always recovered with this simple timeout fix and I have not had to power cycle them as discussed.

I am wondering if this "hang" is more  related to the behavior of PulseIn rather than to the HCSR04 hardware. I'll try to look into that.

In any case, I think this is a useful change. I like having timeouts on loops ;-)  I'll put in the PR this evening.

**Comment by mmabey** [comment]
Interesting that there's that much variance, but not surprising. That may be why I didn't ever experience problems with my own unit.

I would lean toward using a timeout value that is justifiable based on known limitations. What I mean by that is, if there is a typical range limit for the different brands of sensors, say 5 meters for example (10 m round trip), and we figure out how long we would normally have to wait for that signal, then add a buffer time, say an extra 70%, and use that as the timeout. (I'm assuming [dry air and 20 °C](https://en.wikipedia.org/wiki/Speed_of_sound) here...)

(5 m * 2) / 343 = 0.0291 seconds * 1.70 = ~0.05 s or 50 ms

I'm probably over-engineering the solution, but that's kind of just how my mind works. In any case, it looks like 0.05 seconds should be sufficient and help improve the appearance of not hanging. What are your thoughts? It sounds like you've used more brands of sensors than I have. Do any of them have a range greater than 5 meters?

The possibility of the code hanging being related more to PulseIn is beyond my experience. If you find something there, I would be very interested to know about it.

**Comment by jerryneedell** [comment]
I backed off and set the timeout to .1 sec  -- feel free to override that if you prefer.
I want to be sure that any latency in the code was not going to cause false alarms.
I am not ware of any sensors with longer range than 5m. In fact the less-expensive knock-ff I have seem to have much shorter range.
